---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: Install java-11
    apt:
      name: openjdk-11-jre
      state: absent
      name: openjdk-18-jre
      state: present
      update_cache: yes

  - name: Download maven packages
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
      dest: /opt
  
  - name: Extract packages
    unarchive: 
      src: /opt/apache-maven-3.9.4-bin.tar.gz
      dest: /opt
      remote_src: yes


