---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: Install java-17
    apt:
      name: openjdk-17-jre
      state: present
      update_cache: yes

  - name: Download maven packages
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
      dest: /opt
  
  - name: Extract packages
    unarchive: 
      src: /opt/apache-maven-3.9.4-bin.tar.gz
      dest: /opt
      remote_src: yes

  - name: Install docker
    apt:
      name: docker.io
      state: present

  - name: Start docker
    service:
      name: docker
      state: started

  - name: Enable docker service
    service:
      name: docker
      enabled: yes

  
 

